language: node_js
dist: trusty
sudo: required
node_js:
 # Use the explicit NodeJS LTS version 8.9.4 to avoid any automatic upgrade of the version.
  - '8.9.4'

addons:
    chrome: stable
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"

before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - sleep 3 # give xvfb some time to start

# install: npm install

#script:
#  - npm run test

#cache:
#  directories:
#  - node_modules

jobs:
  include:
    - stage: generator
      install: npm install
      script:
        - npm run test
      cache:
        directories:
        - node_modules
    - stage: acs
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: cd app/templates/adf-cli-acs-template && npm install && npm test -- --watch=false
    - stage: acs-e2e
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: ./scripts/test-e2e.sh --proxy $E2E_HOST -host "localhost:4200"  -u "$E2E_USERNAME" -p "$E2E_PASSWORD" -e "$E2E_USERNAME" -save --skip-lint -b -f adf-cli-acs-template
    - stage: aps
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: cd app/templates/adf-cli-aps-template && npm install && npm test -- --watch=false
    - stage: aps-e2e
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: ./scripts/test-e2e.sh --proxy $E2E_HOST -host "localhost:4200"  -u "$E2E_USERNAME" -p "$E2E_PASSWORD" -e "$E2E_USERNAME" -save --skip-lint -b -s sidebar_component.e2e.ts
    - stage: acs-aps
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: cd app/templates/adf-cli-acs-aps-template && npm install && npm test -- --watch=false
    - stage: acs-aps-e2e
      before_install:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
      script: ./scripts/test-e2e.sh --proxy $E2E_HOST -host "localhost:4200"  -u "$E2E_USERNAME" -p "$E2E_PASSWORD" -e "$E2E_USERNAME" -save --skip-lint -b -f adf-cli-acs-aps-template
